#!/bin/bash

echo "🚀 Cloudflare Pages Migration Setup"
echo "===================================="

echo ""
echo "📝 Web app migration completed successfully!"
echo ""
echo "✅ What's been done:"
echo "   - Removed Vercel configuration (vercel.json)"
echo "   - Created wrangler.toml for Cloudflare Pages"
echo "   - Updated package.json with Pages deployment scripts"
echo "   - Added wrangler as dev dependency"
echo "   - Updated environment variable examples"
echo "   - Built the application successfully"
echo ""
echo "🔧 Current Status:"
echo "   ✅ Web app runs on: http://localhost:5173"
echo "   ✅ API runs on: http://localhost:8787" 
echo "   ✅ API calls automatically connect to Cloudflare Workers"
echo ""
echo "🚀 Next steps to deploy to Cloudflare Pages:"
echo ""
echo "1. Create a Cloudflare Pages project:"
echo "   wrangler pages create event-loop-web"
echo ""
echo "2. Deploy to Pages:"
echo "   npm run pages:deploy"
echo ""
echo "3. Set up environment variables in production:"
echo "   wrangler pages secret put VITE_CLERK_PUBLISHABLE_KEY"
echo "   wrangler pages secret put VITE_API_URL"
echo ""
echo "4. For production API URL, update to your deployed Workers URL:"
echo "   VITE_API_URL=https://event-loop-api.your-subdomain.workers.dev"
echo ""
echo "📋 Available Scripts:"
echo "   npm run dev                    # Local Vite dev server"
echo "   npm run build                  # Build for production"
echo "   npm run pages:dev             # Cloudflare Pages local dev"
echo "   npm run pages:deploy          # Deploy to Pages preview"
echo "   npm run pages:deploy:production # Deploy to Pages production"
echo ""
echo "🎯 Migration Status:"
echo "   ✅ API: Migrated to Cloudflare Workers + D1"
echo "   ✅ Web: Migrated to Cloudflare Pages setup"
echo "   ✅ Full stack now runs on Cloudflare infrastructure!"
echo ""
