name = "event-loop-web"
compatibility_date = "2024-12-18"
pages_build_output_dir = "dist"

[env.production.vars]
VITE_CLERK_PUBLISHABLE_KEY = ""  # Will be set via wrangler pages secret
VITE_API_URL = ""  # Will be set to your deployed Workers URL

[env.preview.vars]
VITE_CLERK_PUBLISHABLE_KEY = ""  # Will be set via wrangler pages secret
VITE_API_URL = ""  # Will be set to your deployed Workers URL

# The build configuration is handled by Vite
# so we don't need additional build settings here
