version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: eventloop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eventloop
      POSTGRES_PASSWORD: eventloop
      POSTGRES_DB: eventloop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
